# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for zerodim
# Generated by tesseract 0.9.0 on 2025-07-07T15:18:43.972231


import numpy as np
from pydantic import BaseModel, Field
from tesseract_core.runtime import Array, Int64


class InputSchema(BaseModel):
    max_num: int = Field(description="Endpoint for a sum of natural numbers.")


class OutputSchema(BaseModel):
    nat_sum: Array[
        (),
        Int64,
    ] = Field(description="Sum of natural numbers.")


def apply(inputs: InputSchema) -> OutputSchema:
    """Takes the sum of the natural numbers up to max_num."""
    return OutputSchema(nat_sum=np.arange(inputs.max_num).sum())
