name: Test installation via pip

on:
    # run on PRs for validation
    pull_request:
      paths:
        - "requirements.txt"
        - "pyproject.toml"


jobs:
  test-pip-install:
    name: "Test pip install"
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install -r requirements.txt \
            --extra-index-url https://pypi.org/simple
          pip install --no-deps .
